<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLApiA4j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLApiA4j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLApiA4j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLApiA4j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLApiA4j\App_KernelDevDebugContainer([
    'container.build_hash' => 'LApiA4j',
    'container.build_id' => '5a0bd34e',
    'container.build_time' => 1695306790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLApiA4j');
