<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOXTaM1x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOXTaM1x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOXTaM1x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOXTaM1x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOXTaM1x\App_KernelDevDebugContainer([
    'container.build_hash' => 'OXTaM1x',
    'container.build_id' => 'c4bc4ae4',
    'container.build_time' => 1695278628,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOXTaM1x');
