<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV0EXAVV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV0EXAVV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV0EXAVV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV0EXAVV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV0EXAVV\App_KernelDevDebugContainer([
    'container.build_hash' => 'V0EXAVV',
    'container.build_id' => 'df107f39',
    'container.build_time' => 1695203674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV0EXAVV');
