<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'relation_user', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'order_num', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'pain', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'viande', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'sauce', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'frites', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'boisson'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'relation_user', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'order_num', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'pain', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'viande', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'sauce', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'frites', '' . "\0" . 'App\\Entity\\Order' . "\0" . 'boisson'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelationUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelationUser', []);

        return parent::getRelationUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelationUser(?\App\Entity\User $relation_user): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelationUser', [$relation_user]);

        return parent::setRelationUser($relation_user);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderNum(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderNum', []);

        return parent::getOrderNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderNum(int $order_num): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderNum', [$order_num]);

        return parent::setOrderNum($order_num);
    }

    /**
     * {@inheritDoc}
     */
    public function getPain(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPain', []);

        return parent::getPain();
    }

    /**
     * {@inheritDoc}
     */
    public function setPain(string $pain): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPain', [$pain]);

        return parent::setPain($pain);
    }

    /**
     * {@inheritDoc}
     */
    public function getViande(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViande', []);

        return parent::getViande();
    }

    /**
     * {@inheritDoc}
     */
    public function setViande(string $viande): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViande', [$viande]);

        return parent::setViande($viande);
    }

    /**
     * {@inheritDoc}
     */
    public function getSauce(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSauce', []);

        return parent::getSauce();
    }

    /**
     * {@inheritDoc}
     */
    public function setSauce(string $sauce): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSauce', [$sauce]);

        return parent::setSauce($sauce);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrites(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrites', []);

        return parent::getFrites();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrites(string $frites): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrites', [$frites]);

        return parent::setFrites($frites);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoisson(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoisson', []);

        return parent::getBoisson();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoisson(string $boisson): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoisson', [$boisson]);

        return parent::setBoisson($boisson);
    }

}
